const mods=['Groen & klimaat','Sociale veiligheid','Ontmoeting','Mobiliteit','Voorzieningen','Demografie','Openbare ruimte','Participatie'],score=[['Groen',46],['Veiligheid',58],['Ontmoeting',37],['Mobiliteit',71],['Leefbaarheid',63],['Klimaat',42]],ops=['Gebrek aan informele ontmoetingsplekken','Onvoldoende schaduw en verkoeling','Zwakke ogen op straat','Onveilige oversteekbaarheid','Versnipperde groene ruimte'],k=[
{id:1,t:'Koele ontmoetingsplek',th:'groen',c:91,p:[52.3667,4.8351],why:['boomdek 9%','school op 80 m','brede stoep'],ints:['Klimaatbank','Regentuin','Drinkwaterpunt','Speelaanleiding']},
{id:2,t:'Ogen op straat versterken',th:'veiligheid',c:88,p:[52.3653,4.8316],why:['blinde gevel','weinig entrees','lage avondactiviteit'],ints:['Nieuwe entrees','Transparante plint','Gevelzitplek','Warme verlichting']},
{id:3,t:'Buurtkamer aan plein',th:'ontmoeting',c:86,p:[52.3681,4.8328],why:['supermarkt','OV-halte','veel passanten'],ints:['Buurtkamer','Open plint','Buurtkast','Flexibel terras']},
{id:4,t:'Veilige oversteek',th:'mobiliteit',c:84,p:[52.3675,4.8387],why:['brede rijbaan','schoolroute','slechte zichtlijn'],ints:['Middeneiland','Stoepuitstulping','Verhoogd plateau','Routeverlichting']},
{id:5,t:'Pocket park in restzone',th:'groen',c:80,p:[52.3639,4.8369],why:['veel verharding','weinig biodiversiteit','ruimte beschikbaar'],ints:['Pocket park','Wadi','Inheemse beplanting','Picknicktafel']},
{id:6,t:'Collectieve voortuin',th:'ontmoeting',c:78,p:[52.3648,4.8402],why:['galerijwoningen','anonieme plint','brede setback'],ints:['Geveltuinen','Deelbank','Bloembakken','Entreecluster']},
{id:7,t:'Avondroute verbeteren',th:'veiligheid',c:75,p:[52.369,4.837],why:['donkere route','weinig zicht','participatiesignaal'],ints:['Verlichting','Zichtlijnen','Oriëntatiepunten','Actieve plint']},
{id:8,t:'Schoolstraat als verblijfsplek',th:'mobiliteit',c:73,p:[52.366,4.8289],why:['school','piekverkeer','weinig speelruimte'],ints:['Tijdelijke afsluiting','Speelmarkering','Wachtbank','Fietsparkeren']}];
modules.innerHTML=mods.map((x,i)=>`<div class="module" data-m="${i}"><span>${x}</span><b>Gereed</b></div>`).join('');
const map=L.map('map').setView([52.3665,4.835],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);L.polygon([[52.3712,4.8271],[52.3714,4.8409],[52.3658,4.8441],[52.3614,4.8398],[52.3619,4.829],[52.366,4.8259]],{color:'#b95555',fillOpacity:.06,dashArray:'6 5'}).addTo(map);let markers=[];
function draw(){scores.innerHTML='<h2>Gebiedsprofiel · score 58</h2>'+score.map(x=>`<div class="score"><span>${x[0]}</span><div><i style="width:${x[1]}%"></i></div><b>${x[1]}</b></div>`).join('');opgaven.innerHTML='<h2>Belangrijkste opgaven</h2>'+ops.map((x,i)=>`<div class="card"><b>${i+1}. ${x}</b><p>Voorbeeldopgave op basis van gecombineerde indicatoren.</p></div>`).join('');kansen.innerHTML='<h2>8 kansrijke locaties</h2>'+k.map(x=>`<div class="card chance" data-id="${x.id}"><small class="${x.th}">${x.th}</small><b> ${x.t}</b><p>${x.c}% potentie · ${x.why.join(' · ')}</p></div>`).join('');document.querySelectorAll('.chance').forEach(x=>x.onclick=()=>detail(+x.dataset.id))}
function pins(){k.forEach(x=>{let icon=L.divIcon({className:'',html:`<div class="pin pin-${x.th}"></div>`,iconSize:[22,22]});let m=L.marker(x.p,{icon}).addTo(map);m.th=x.th;m.on('click',()=>detail(x.id));m.bindTooltip(`<b>${x.t}</b><br>${x.c}% potentie`);markers.push(m)})}
function detail(id){let x=k.find(y=>y.id===id);detail.innerHTML=`<small class="${x.th}">${x.th}</small><h2>${x.t}</h2><p>Potentie ${x.c}%</p><h3>Waarom deze locatie?</h3><ul>${x.why.map(y=>`<li>${y}</li>`).join('')}</ul><h3>Interventies</h3><ul>${x.ints.map(y=>`<li>${y}</li>`).join('')}</ul>`;drawer.classList.remove('hide');map.panTo(x.p)}
run.onclick=()=>{overlay.classList.remove('hide');let n=0,t=setInterval(()=>{status.textContent=mods[n]+' analyseren…';bar.style.width=((n+1)/mods.length*100)+'%';let m=document.querySelector(`[data-m="${n}"]`);m.classList.add('done');m.querySelector('b').textContent='Geanalyseerd';n++;if(n===mods.length){clearInterval(t);setTimeout(()=>{overlay.classList.add('hide');empty.classList.add('hide');scores.classList.remove('hide');draw();pins()},400)}},300)};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.t).classList.add('active')});document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');markers.forEach(m=>{let s=b.dataset.f==='all'||m.th===b.dataset.f;if(s&&!map.hasLayer(m))m.addTo(map);if(!s&&map.hasLayer(m))map.removeLayer(m)})});